linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - golint
    - gosimple
    - ineffassign
    - interfacer
    - misspell
    - staticcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow
    - errcheck

run:

  # timeout for analysis
  timeout: 10m

  # include test files or not, default is true
  tests: false

  skip-dirs:
    - hack
    - docs

issues:

  # List of regexps of issue texts to exclude
  exclude:
    - "comment on"
    - "error should be the last"
    - "should have comment"
